In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv("/content/Retail_Dataset_Modified.csv")
print("Dataset Loaded Successfully")
df

Dataset Loaded Successfully

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [ ]:
print(df.head())

         Store_ID                      Store_Name    Brand_Name    Store_Type  \
0     BX_PUNE_034    BrandX_India Superstore Pune  BrandX_India      Flagship
1   BX_MUMBAI_023  BrandX_India Superstore Mumbai  BrandX_India  Street Store
2     BX_PUNE_073        BrandX_India Trends Pune  BrandX_India      Flagship
3  BX_CHENNAI_061     BrandX_India Trends Chennai  BrandX_India    Mall Store
4  BX_CHENNAI_033    BrandX_India Connect Chennai  BrandX_India    Mall Store

      City City_Tier     Product_Name   Category     Sub_Category  \
0     Pune     Tier1   Green Tea 100g  Groceries              Tea
1   Mumbai     Metro  White Sugar 1kg  Groceries            Sugar
2     Pune     Tier1   Levi's T-Shirt    Clothes         T-Shirts
3  Chennai     Metro    Adidas Hoodie    Clothes          Jackets
4  Chennai     Metro    PlayStation 5    Gadgets  Gaming Consoles

  Product_Stage  ... Brand_Loyalty Brand_Awareness  Price_Competitiveness  \
0     Declining  ...          70.8            75.7               Standard
1     Declining  ...          80.5            81.5            Competitive
2     Declining  ...          68.5            76.7               Standard
3    New Launch  ...          92.4            88.0            Competitive
4     Declining  ...          82.9            89.5            Competitive

   Weather_Impact Delivery_Time  Shipping_Cost  Month  Year  Quarter  Season
0             Low           6.0             57      1  2022       Q1  Spring
1             Low           4.0             99      1  2022       Q1  Spring
2          Medium           4.0            101      1  2022       Q1  Spring
3          Medium           5.0             79      1  2022       Q1  Spring
4             Low           2.0            110      1  2022       Q1  Spring

[5 rows x 47 columns]

In [ ]:
print(df.tail())

           Store_ID                       Store_Name    Brand_Name  \
5166  BX_JAIPUR_077        BrandX_India Style Jaipur  BrandX_India
5167  BX_MUMBAI_067        BrandX_India Daily Mumbai  BrandX_India
5168  BX_KANPUR_097  BrandX_India Gadget Zone Kanpur  BrandX_India
5169  BX_MUMBAI_031        BrandX_India Style Mumbai  BrandX_India
5170   BX_DELHI_032   BrandX_India Electronics Delhi  BrandX_India

        Store_Type     City City_Tier     Product_Name     Category  \
5166  Street Store  Jaipur      Tier2       Pepe Jeans      Clothes
5167       Express  Mumbai      Metro  White Sugar 1kg    Groceries
5168      Flagship  Kanpur      Tier2      Dell XPS 13  Electronics
5169  Street Store  Mumbai      Metro     Nike Air Max      Clothes
5170      Flagship   Delhi      Metro   MacBook Air M2  Electronics

     Sub_Category Product_Stage  ... Brand_Loyalty Brand_Awareness  \
5166        Jeans     Declining  ...          91.3            68.7
5167        Sugar       Growing  ...          81.6            82.0
5168      Laptops  Discontinued  ...          89.9            68.1
5169        Shoes        Mature  ...          80.6            86.5
5170      Laptops     Declining  ...          91.8            85.0

      Price_Competitiveness  Weather_Impact Delivery_Time  Shipping_Cost  \
5166               Standard          Medium           3.0            150
5167            Competitive             Low           7.0            136
5168               Standard             Low           1.0            222
5169            Competitive          Medium           3.0            138
5170            Competitive             Low           3.0            210

      Month  Year  Quarter   Season
5166     11  2024       Q4   Winter
5167      7  2023       Q3  Monsoon
5168      7  2023       Q3  Monsoon
5169     12  2022       Q4   Winter
5170      6  2024       Q2  Monsoon

[5 rows x 47 columns]

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   object
 1   Store_Name             5171 non-null   object
 2   Brand_Name             5171 non-null   object
 3   Store_Type             5171 non-null   object
 4   City                   5109 non-null   object
 5   City_Tier              5171 non-null   object
 6   Product_Name           5098 non-null   object
 7   Category               5171 non-null   object
 8   Sub_Category           5171 non-null   object
 9   Product_Stage          5171 non-null   object
 10  Quantity_Available     5171 non-null   object
 11  Units_Sold             5171 non-null   object
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   object
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   object
 20  Sales_Channel          5171 non-null   object
 21  Payment_Method         5171 non-null   object
 22  Supplier               5103 non-null   object
 23  Supplier_Rating        5171 non-null   object
 24  Promotion_Type         5171 non-null   object
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   object
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   object
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   object
 40  Weather_Impact         5171 non-null   object
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   object
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   object
 46  Season                 5171 non-null   object
dtypes: float64(11), int64(10), object(26)
memory usage: 1.9+ MB
None

In [ ]:
print(df.columns)

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [ ]:
print(df.shape)

(5171, 47)

In [ ]:
df.describe()

,Unit_Price,Cost_Price,Profit_Margin,Average_Order_Value,Inventory_Turnover,Days_of_Stock,Promotion_Impact,Max_Discount_Offered,Return_Rate,Customer_Satisfaction,...,Review_Count,Sales_Rep_Experience,Sales_Rep_Rating,Market_Share,Competitor_Count,Brand_Loyalty,Brand_Awareness,Delivery_Time,Month,Year
count,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5094.000000,...,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5111.000000,5171.000000,5171.000000
mean,36147.283117,28008.718236,22.455080,45000.251789,3.928517,142.718816,20.979791,22.679172,4.018294,4.209109,...,256.498936,5.548250,4.248018,15.406556,16.231483,81.351228,80.307097,3.984934,6.567588,2023.016438
std,53910.395954,41848.286241,4.349469,67405.809814,2.284159,128.281114,12.212204,15.784690,2.292903,0.280465,...,140.948535,2.861696,0.433274,6.009766,6.646939,8.018098,8.542352,2.021598,3.463351,0.814235
min,36.000000,28.000000,14.680000,41.000000,0.300000,32.000000,0.000000,0.000000,0.000000,3.600000,...,10.000000,1.000000,3.500000,3.000000,3.000000,67.000000,60.000000,1.000000,1.000000,2022.000000
25%,2016.500000,1548.500000,18.675000,2476.000000,2.220000,68.000000,13.100000,9.000000,2.000000,4.000000,...,138.000000,3.000000,3.900000,11.300000,11.000000,75.900000,77.700000,2.000000,4.000000,2022.000000
50%,11816.000000,9136.000000,22.450000,14734.000000,3.440000,105.000000,22.300000,22.000000,4.100000,4.200000,...,256.000000,6.000000,4.200000,14.900000,18.000000,80.400000,83.000000,4.000000,7.000000,2023.000000
75%,53778.500000,41569.000000,26.235000,66630.000000,5.260000,162.000000,31.200000,36.000000,6.000000,4.400000,...,378.000000,8.000000,4.600000,18.900000,22.000000,84.600000,86.600000,6.000000,10.000000,2024.000000
max,307651.000000,252171.000000,30.430000,450890.000000,11.100000,1200.000000,40.000000,50.000000,8.000000,4.900000,...,500.000000,10.000000,5.000000,30.000000,25.000000,100.000000,90.000000,7.000000,12.000000,2024.000000